### ISSUE TITLE
Output of log_batch_dot

### ISSUE THREAD

**Issue by awasthiabhijeet** [liuhu-bigeye/enctc.crnn#10]
Hi @liuhu-bigeye 
https://github.com/liuhu-bigeye/enctc.crnn/blob/de22c76f55b86a19c3fb6f9b1b882bbda09a56dd/pytorch_ctc/m_ctc.py#L95

Could you kindly confirm whether the output of the log_batch_dot function can have a positive entry? 
(I believe no because these are supposed to be log probabilities)

**Comment by liuhu-bigeye** [comment]
Right

**Comment by awasthiabhijeet** [comment]
I am observing a few cases where this condition gets violated. There are positive elements in out in these cases.
Not sure how to reproduce the error exactly :(

Did you encounter this problem too?

**Comment by liuhu-bigeye** [comment]
Suggestions:

1. Try from short sequence and compare to https://github.com/baidu-research/warp-ctc.
2. For extremely long sequences, try to use DoubleTensor.
3. If none of the above works, may you provide a reproducible UT?
