### ISSUE TITLE
Case of non zero blank

### ISSUE THREAD

**Issue by awasthiabhijeet** [liuhu-bigeye/enctc.crnn#9]
https://github.com/liuhu-bigeye/enctc.crnn/blob/de22c76f55b86a19c3fb6f9b1b882bbda09a56dd/pytorch_ctc/m_ctc.py#L141

Hi,
I believe the argument `blank` of `ctc_loss_log` is not being used properly. It seems blank_id is assumed to be 0 inside the function instead of making use of the argument `blank`
When blank is not 0 (and represented by some other number), line 141 and 142 needs to be changed accordingly, right?

**Comment by awasthiabhijeet** [comment]
@jin-s13 @liuhu-bigeye

**Comment by liuhu-bigeye** [comment]
Thanks for your comment!
The `blank` argument does not works not only in `ctc_loss_log` but also in other functions under folder `pytorch_ctc`.

A quick fix is pushed at branch [blank_dev](https://github.com/liuhu-bigeye/enctc.crnn/tree/blank_dev), please check if this  satisfies you.

**Comment by awasthiabhijeet** [comment]
Hi, 
The changes do serve the purpose.
Thank you for your reply. :)
